import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Cult4Config } from "./config.js";
import { getConfig } from "./config.js";

export function materializeCult4Tools(
  config: Cult4Config = getConfig(),
): string {
  mkdirSync(config.toolsPath, { recursive: true, mode: 0o700 });
  const path = join(config.toolsPath, "cult4.ts");
  const definitions = [
    'export const bootstrap=tool({description:"Load authoritative scoped Cult4 context",args:{},execute:(a,c)=>call("bootstrap",a,c)})',
    'export const get_work=tool({description:"Get the assigned WorkItem",args:{},execute:(a,c)=>call("get_work",a,c)})',
    'export const create_work=tool({description:"Propose request-linked work with explicit required capabilities; Cult4 routes it to an operationally equipped specialist",args:{type:s.string(),title:s.string(),goal:s.string(),requestIds:s.array(s.string()).min(1),requiredCapabilities:s.array(s.string()).min(1).optional(),priority:s.number().int().min(0).max(100).optional(),risk:s.enum(["LOW","MEDIUM","HIGH","CRITICAL"]).optional(),assignedTo:s.string().optional(),parentId:s.string().optional()},execute:(a,c)=>call("create_work",a,c)})',
    'export const add_work_dependency=tool({description:"Add a dependency between two Operator-created WorkItems in the current Business",args:{workItemId:s.string(),dependsOnWorkItemId:s.string()},execute:(a,c)=>call("add_work_dependency",a,c)})',
    'export const ready_work=tool({description:"Admit an Operator-created proposed WorkItem to bounded execution after its graph and assignment are ready",args:{workItemId:s.string()},execute:(a,c)=>call("ready_work",a,c)})',
    'export const update_work=tool({description:"Transition the assigned WorkItem",args:{status:s.enum(["READY","RUNNING","WAITING_GATE","WAITING_HUMAN","WAITING_EXTERNAL","BLOCKED","FAILED","DONE","CANCELLED"]),result:s.string().optional()},execute:(a,c)=>call("update_work",a,c)})',
    'export const get_state=tool({description:"Get compact authoritative business state",args:{},execute:(a,c)=>call("get_state",a,c)})',
    'export const sync_intake=tool({description:"Capture and return the exact immutable human messages in this Intake before constructing official requests",args:{},execute:(a,c)=>call("sync_intake",a,c)})',
    'export const propose_business_mandate=tool({description:"Capture the exact Intake transcript and propose a mandate with complete official-request coverage; no human point may silently disappear",args:{purpose:s.string().min(10),customer:s.string().min(10),offer:s.string().min(10),narrative:s.string().min(160),spirit:s.string().min(80),voice:s.string().min(40),taste:s.string().min(40),emotionalTerritory:s.string().min(40),qualityBar:s.string().min(40),autonomyMode:s.enum(["ASSISTED","SUPERVISED","BOUNDED_AUTONOMOUS"]),constraints:s.array(s.string().min(10)).min(1),allowedWithoutApproval:s.array(s.string().min(10)).min(1),requiresApproval:s.array(s.string().min(10)).min(1),prohibited:s.array(s.string().min(10)).min(1),antiGoals:s.array(s.string().min(10)).min(1),successSignals:s.array(s.string().min(10)).min(1),stopConditions:s.array(s.string().min(10)).min(1),humanInputs:s.array(s.string().min(10)).min(1),unresolvedQuestions:s.array(s.string().min(10)),officialRequests:s.array(s.object({statement:s.string().min(10),kind:s.enum(["OUTCOME","CAPABILITY","INTEGRATION","CONSTRAINT","PREFERENCE","IDEA","QUALITY","OPERATION"]),priority:s.enum(["MUST","SHOULD","MAY"]),acceptanceCriteria:s.string().min(20),sourceMessageIds:s.array(s.string()).min(1),disposition:s.enum(["COMMITTED","IDEA_TO_EXPLORE","DEFERRED","REJECTED","SUPERSEDED_BY_USER"]),contractReference:s.string().min(3),rationale:s.string().min(10),deviationRequestId:s.string().optional()})).min(1),messageDispositions:s.array(s.object({messageId:s.string(),disposition:s.enum(["NON_SUBSTANTIVE","CONTEXT_ONLY","SUPERSEDED_BY_USER"]),rationale:s.string().min(10)})),budget:s.object({currency:s.string().min(3).max(3),maxExplorationSpendCents:s.number().int().min(0),maxSpendWithoutApprovalCents:s.number().int().min(0),maxSingleSpendCents:s.number().int().min(0)})},execute:(a,c)=>call("propose_business_mandate",a,c)})',
    'export const finish_intake=tool({description:"End a completed intake and hand the exact pending mandate to the trusted Cult4 host for separate human confirmation; this never approves the mandate",args:{mandateId:s.string(),contentHash:s.string().length(64)},execute:(a,c)=>call("finish_intake",a,c)})',
    'export const start_autopilot=tool({description:"Hand sustained autonomous execution to the bounded Cult4 host loop after the human explicitly asks to proceed; requires confirmed mandate and ready durable work",args:{maxDurationMinutes:s.number().int().min(1).max(180).optional(),maxWorkItems:s.number().int().min(1).max(200).optional(),maxCostCents:s.number().int().min(1).max(2000).optional()},execute:(a,c)=>call("start_autopilot",a,c)})',
    'export const search_memory=tool({description:"Search only allowed memory scopes",args:{query:s.string(),limit:s.number().int().min(1).max(20).optional()},execute:(a,c)=>call("search_memory",a,c)})',
    'export const remember=tool({description:"Record scoped learning; volatile facts should expire",args:{kind:s.enum(["observation","hypothesis","external_evidence","procedure","postmortem","decision","warning"]),scope:s.enum(["employee","business","employee_business"]),title:s.string(),content:s.string(),sourceRef:s.string().optional(),confidence:s.number().min(0).max(1).optional(),expiresAt:s.string().optional()},execute:(a,c)=>call("remember",a,c)})',
    'export const record_source=tool({description:"Record source provenance and methodology metadata",args:{type:s.string(),title:s.string(),author:s.string().optional(),publisher:s.string().optional(),locator:s.string().optional(),publicationDate:s.string().optional(),accessNotes:s.string().optional(),licenseNotes:s.string().optional(),metadata:s.record(s.string(),s.unknown()).optional()},execute:(a,c)=>call("record_source",a,c)})',
    'export const record_claim=tool({description:"Record a claim separately from evidence",args:{statement:s.string(),status:s.enum(["HYPOTHESIS","SUPPORTED","CONTRADICTED","UNRESOLVED"]).optional()},execute:(a,c)=>call("record_claim",a,c)})',
    'export const record_evidence=tool({description:"Attach provenance-aware evidence and epistemic status",args:{claimId:s.string(),sourceId:s.string().optional(),summary:s.string(),reliability:s.number().min(0).max(1).optional(),applicability:s.number().min(0).max(1).optional(),confidence:s.number().min(0).max(1).optional(),contradiction:s.boolean().optional(),observedAt:s.string().optional(),observationType:s.enum(["OBSERVED","ESTIMATED","INFERRED","UNKNOWN"]).optional(),metadata:s.record(s.string(),s.unknown()).optional()},execute:(a,c)=>call("record_evidence",a,c)})',
    'export const record_decision=tool({description:"Record a reconstructible material decision and identify the material claims it depends on",args:{statement:s.string(),rationale:s.string(),alternatives:s.array(s.string()),unknowns:s.array(s.string()),risk:s.enum(["LOW","MEDIUM","HIGH","CRITICAL"]),evidenceIds:s.array(s.string()).optional(),materialClaimIds:s.array(s.string()).min(1).optional(),subjectType:s.string().optional(),subjectId:s.string().optional(),subjectVersion:s.string().optional()},execute:(a,c)=>call("record_decision",a,c)})',
    'export const register_control=tool({description:"Declare a Business-owned executable control; new code versions are EXPERIMENTAL until independently verified",args:{slug:s.string(),description:s.string(),validationCommand:s.string(),requiredActions:s.array(s.enum(["SPEND_MONEY","ORDER_PHYSICAL_SAMPLE","PUBLISH_PRODUCT","SEND_PUBLIC_MESSAGE","SIGN_COMMITMENT","CREATE_EXTERNAL_ACCOUNT"])).min(1),codeVersion:s.string()},execute:(a,c)=>call("register_control",a,c)})',
    'export const record_control_validation=tool({description:"Record version-bound control evidence; QA_VERIFIED requires an independent DIGITAL_QA WorkItem",args:{controlId:s.string(),subjectType:s.string(),subjectId:s.string(),subjectVersion:s.string().optional(),inputHash:s.string().optional(),result:s.enum(["PASS","FAIL"]),level:s.enum(["TESTED","QA_VERIFIED"]),evidence:s.array(s.string()).min(1),expiresAt:s.string().optional()},execute:(a,c)=>call("record_control_validation",a,c)})',
    'export const evaluate_action=tool({description:"Evaluate a structured action and derive deterministic gates",args:{actionType:s.enum(["PUBLISH_PRODUCT","SPEND_MONEY","CREATE_EXTERNAL_ACCOUNT","SEND_PUBLIC_MESSAGE","SIGN_COMMITMENT","RELEASE_CODE","ORDER_PHYSICAL_SAMPLE","DESIGN_READY","FOUNDATION_CHANGE"]),subjectType:s.string(),subjectId:s.string(),subjectVersion:s.string(),amount:s.number().int().positive().optional(),currency:s.string().optional(),destination:s.string().optional(),metadata:s.record(s.string(),s.unknown()).optional()},execute:(a,c)=>call("evaluate_action",a,c)})',
    'export const request_human=tool({description:"Create a durable HumanRequest; silence never approves",args:{gateId:s.string().optional(),type:s.enum(["APPROVAL","DECISION","INFORMATION","PHYSICAL_ACTION","IDENTITY_VERIFICATION","AESTHETIC_REVIEW","LEGAL_REVIEW","PHYSICAL_INSPECTION","CULTURAL_JUDGMENT","LOCAL_LANGUAGE_JUDGMENT","BRAND_RISK_JUDGMENT"]),requestedResponsibility:s.string().optional(),subjectType:s.string(),subjectId:s.string(),subjectVersion:s.string(),title:s.string(),context:s.string(),recommendation:s.string().optional(),options:s.array(s.string()).optional(),remindAt:s.string().optional(),expiresAt:s.string().optional()},execute:(a,c)=>call("request_human",a,c)})',
    'export const verify_official_request=tool({description:"Independent QA records exact acceptance evidence for an official human request",args:{requestId:s.string(),workItemId:s.string(),subjectType:s.string(),subjectId:s.string(),subjectVersion:s.string(),result:s.enum(["PASS","FAIL","PARTIAL"]),evidence:s.array(s.string()).min(1)},execute:(a,c)=>call("verify_official_request",a,c)})',
    'export const request_spend=tool({description:"Request spend through the transactional broker",args:{amount:s.number().int().positive(),currency:s.string(),vendor:s.string(),purpose:s.string(),budgetId:s.string(),risk:s.enum(["LOW","MEDIUM","HIGH"]).optional(),legalRisk:s.boolean().optional(),recurring:s.boolean().optional(),idempotencyKey:s.string().optional()},execute:(a,c)=>call("request_spend",a,c)})',
    'export const record_artifact_source=tool({description:"Record commercial artifact provenance",args:{artifactVersionId:s.string(),sourceType:s.string(),sourceRef:s.string(),licenseStatus:s.enum(["VERIFIED","UNVERIFIED","NOT_REQUIRED"]),notes:s.string().optional()},execute:(a,c)=>call("record_artifact_source",a,c)})',
    'export const create_market_study=tool({description:"Create and start a structured MarketStudy",args:{initiativeId:s.string().optional(),targetSegment:s.string(),market:s.string(),language:s.string().optional(),geography:s.string().optional(),researchQuestion:s.string(),methodology:s.string().optional(),replacesMarketStudyId:s.string().optional()},execute:(a,c)=>call("create_market_study",a,c)})',
    'export const attach_market_evidence=tool({description:"Attach Evidence to a MarketStudy",args:{marketStudyId:s.string(),evidenceId:s.string(),role:s.enum(["SUPPORTING","CONTRADICTING","CONTEXTUAL","COMMERCIAL","SATURATION","CULTURAL","RISK","METHODOLOGY"])},execute:(a,c)=>call("attach_market_evidence",a,c)})',
    'export const add_market_signal=tool({description:"Add an evidence-linked market signal",args:{marketStudyId:s.string(),kind:s.enum(["CULTURAL","COMMERCIAL","OPPORTUNITY","SATURATION","RISK"]),subtype:s.string().optional(),title:s.string(),description:s.string(),lifecycle:s.enum(["EMERGING","RISING","MAINSTREAM","SATURATED","DECLINING","DEAD","UNKNOWN"]).optional(),confidence:s.enum(["LOW","MEDIUM","HIGH","UNKNOWN"]),observedAt:s.string().optional(),expiresAt:s.string().optional(),evidenceIds:s.array(s.string()).optional()},execute:(a,c)=>call("add_market_signal",a,c)})',
    'export const complete_market_study=tool({description:"Complete a study only when its deterministic contract passes",args:{marketStudyId:s.string(),summary:s.string(),confidence:s.enum(["LOW","MEDIUM","HIGH"]),validUntil:s.string(),methodology:s.string(),limitations:s.string(),counterSignalSearched:s.boolean(),counterSignalSummary:s.string().optional()},execute:(a,c)=>call("complete_market_study",a,c)})',
    'export const get_market_study=tool({description:"Get a synthesized MarketStudy",args:{marketStudyId:s.string()},execute:(a,c)=>call("get_market_study",a,c)})',
    'export const create_creative_brief=tool({description:"Create the Strategist handoff from current market evidence",args:{initiativeId:s.string().optional(),marketStudyId:s.string(),status:s.enum(["DRAFT","READY"]).optional(),targetAudience:s.string(),desiredResponse:s.string().optional(),culturalContext:s.string(),relevantTropes:s.string().optional(),customerLanguage:s.string().optional(),aestheticTerritory:s.string().optional(),saturatedIdeasToAvoid:s.string().optional(),ipDangerAreas:s.string().optional(),commercialConstraints:s.string().optional(),relevantClaimIds:s.array(s.string()).optional(),relevantSignalIds:s.array(s.string()).optional(),validUntil:s.string().optional()},execute:(a,c)=>call("create_creative_brief",a,c)})',
  ];
  const source = [
    'import { tool } from "@opencode-ai/plugin"',
    'import { execFile } from "node:child_process"',
    'import { promisify } from "node:util"',
    "const run=promisify(execFile)",
    'async function call(name,args,context){const {stdout}=await run("cult",["__tool",name,JSON.stringify(args)],{cwd:context.directory,env:{...process.env,CULT4_TOOL_EMPLOYEE:process.env.CULT4_EMPLOYEE??context.agent,CULT4_TOOL_WORK:process.env.CULT4_WORK_ITEM??"",CULT4_TOOL_DIRECTORY:context.directory,CULT4_TOOL_SESSION:context.sessionID??""},maxBuffer:1024*1024});return stdout.trim()}',
    "const s=tool.schema",
    ...definitions,
    "",
  ].join("\n");
  writeFileSync(path, source, { mode: 0o600 });
  chmodSync(path, 0o600);
  return path;
}
